name: CI for schemademo

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
    

jobs:

  ui-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: cd admin/ && npm ci && npm run build
    - run: cd schedule-data-service/ && npm ci
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        browser: chrome
        start: npm run dev

  api-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build-it
    - run: cd schedule-data-service && npm install
    - run: npm install -g newman
    - run: npm install -g pm2
    - run: pm2 start "npm run dev"
    - run: npm run api
    
    
    